In [ ]:
import pandas as pd
from pathlib import Path

column_rename = {
            "CORNOMBRE":"tipo_eleccion",
            "DEP":"coddpto",
            "DEPNOMBRE":"departamento",
            "MUN":"codmpio",
            "MUNNOMBRE":"municipio",
            "CIR":"circunscripcion",
            "PAR":"codigo_partido",
            "CAN":"codigo_lista",
            "CANNOMBRE":"candidato",
            "VOTOS":"votos"
        }
# load_config = {"skipinitialspace":True, "encoding":'unicode_escape', "engine":'python', "sep":';', "skiprows":[3422], "chunksize":30}
        
# Fix 2022_presidencia_primera_vuelta and 2022_presidencia_segunda_vuelta CSV
def stage_2022_presidential():
    df = pd.read_csv("/home/juan-wills/Documents/colombia-elections-analysis-app/data/raw/presidential/2022_presidencia_primera_vuelta.csv",
                        skipinitialspace=True,
                        encoding='unicode_escape',
                        engine='python',
                        sep=';',
                        skiprows=range(1, 13386)
                        # chunksize=5000
                    )
    return df

# Rename columns
df = stage_2022_presidential()

# Rip off "Consulado" rows
cond = df.DEP != 88
df = df[cond]

original_columns = list(column_rename.keys())
df = df.loc[:, original_columns].rename(columns=column_rename)
display(df.head())

senate_path = Path("/home/juan-wills/Documents/colombia-elections-analysis-app/data/staged/presidential/2006_presidencia_2026_06_16_12_14_58.csv")
s_2006 = pd.read_csv(senate_path)
s_2006.head()

,tipo_eleccion,coddpto,departamento,codmpio,municipio,circunscripcion,codigo_partido,codigo_lista,candidato,votos
2,PRESIDENTE,72,VICHADA,1,PUERTO CARREÑO,0,1076,1,RODOLFO HERNÁNDEZ,53
3,PRESIDENTE,72,VICHADA,1,PUERTO CARREÑO,0,998,998,VOTOS NO MARCADOS .,2
4,PRESIDENTE,72,VICHADA,1,PUERTO CARREÑO,0,997,997,VOTOS NULOS .,1
5,PRESIDENTE,72,VICHADA,1,PUERTO CARREÑO,0,996,996,VOTOS EN BLANCO .,5
6,PRESIDENTE,72,VICHADA,1,PUERTO CARREÑO,0,1235,6,GUSTAVO PETRO,48

,id_electoral,tipo_eleccion,coddpto,departamento,codmpio,municipio,circunscripcion,codigo_partido,codigo_lista,primer_apellido,segundo_apellido,nombres,votos,curules,fecha
0,120060000,Presidencia,5,ANTIOQUIA,5001,MEDELLIN,Nacional,19980014.0,1,RINCON,BARRETO,CARLOS ARTURO,669,0,2006-4-28
1,120060000,Presidencia,5,ANTIOQUIA,5001,MEDELLIN,Nacional,19980001.0,2,PAREJO,GONZALEZ,ENRIQUE,986,0,2006-4-28
2,120060000,Presidencia,5,ANTIOQUIA,5001,MEDELLIN,Nacional,20020001.0,3,URIBE,VELEZ,ALVARO,445907,1,2006-4-28
3,120060000,Presidencia,5,ANTIOQUIA,5001,MEDELLIN,Nacional,20050001.0,4,GAVIRIA,DIAZ,CARLOS,107728,0,2006-4-28
4,120060000,Presidencia,5,ANTIOQUIA,5001,MEDELLIN,Nacional,18480001.0,5,SERPA,URIBE,HORACIO,20751,0,2006-4-28

In [18]:
s_2006.fillna({"nombres":' '}, inplace=True)
new_df =s_2006.nombres.str.cat(s_2006['primer_apellido'], sep=' ').str.strip(' .')
new_df.head(10)

0    CARLOS ARTURO RINCON
1          ENRIQUE PAREJO
2            ALVARO URIBE
3          CARLOS GAVIRIA
4           HORACIO SERPA
5            ALVARO LEYVA
6          ANTANAS MOCKUS
7    TARJETAS NO MARCADAS
8             VOTOS NULOS
9         VOTOS EN BLANCO
Name: nombres, dtype: str

In [ ]:
? pd.Series.fillna

Signature:
 pd.Series.fillna(
    self,
    value: 'Hashable | Mapping | Series | DataFrame',
    *,
    axis: 'Axis | None' = None,
    inplace: 'bool' = False,
    limit: 'int | None' = None,
) -> 'Self'
Docstring:
Fill NA/NaN values with `value`.

Parameters
----------
value : scalar, dict, Series, or DataFrame
    Value to use to fill holes (e.g. 0), alternately a
    dict/Series/DataFrame of values specifying which value to use for
    each index (for a Series) or column (for a DataFrame).  Values not
    in the dict/Series/DataFrame will not be filled. This value cannot
    be a list.
axis : {0 or 'index'} for Series, {0 or 'index', 1 or 'columns'} for DataFrame
    Axis along which to fill missing values. For `Series`
    this parameter is unused and defaults to 0.
inplace : bool, default False
    If True, fill in-place. Note: this will modify any
    other views on this object (e.g., a no-copy slice for a column in a
    DataFrame).
limit : int, default None
    This is the maximum number of entries along the entire axis
    where NaNs will be filled. Must be greater than 0 if not None.

Returns
-------
Series/DataFrame
    Object with missing values filled.

See Also
--------
ffill : Fill values by propagating the last valid observation to next valid.
bfill : Fill values by using the next valid observation to fill the gap.
interpolate : Fill NaN values using interpolation.
reindex : Conform object to new index.
asfreq : Convert TimeSeries to specified frequency.

Notes
-----
For non-object dtype, ``value=None`` will use the NA value of the dtype.
See more details in the :ref:`Filling missing data<missing_data.fillna>`
section.

Examples
--------
>>> df = pd.DataFrame(
...     [
...         [np.nan, 2, np.nan, 0],
...         [3, 4, np.nan, 1],
...         [np.nan, np.nan, np.nan, np.nan],
...         [np.nan, 3, np.nan, 4],
...     ],
...     columns=list("ABCD"),
... )
>>> df
     A    B   C    D
0  NaN  2.0 NaN  0.0
1  3.0  4.0 NaN  1.0
2  NaN  NaN NaN  NaN
3  NaN  3.0 NaN  4.0

Replace all NaN elements with 0s.

>>> df.fillna(0)
     A    B    C    D
0  0.0  2.0  0.0  0.0
1  3.0  4.0  0.0  1.0
2  0.0  0.0  0.0  0.0
3  0.0  3.0  0.0  4.0

Replace all NaN elements in column 'A', 'B', 'C', and 'D', with 0, 1,
2, and 3 respectively.

>>> values = {"A": 0, "B": 1, "C": 2, "D": 3}
>>> df.fillna(value=values)
     A    B    C    D
0  0.0  2.0  2.0  0.0
1  3.0  4.0  2.0  1.0
2  0.0  1.0  2.0  3.0
3  0.0  3.0  2.0  4.0

Only replace the first NaN element.

>>> df.fillna(value=values, limit=1)
     A    B    C    D
0  0.0  2.0  2.0  0.0
1  3.0  4.0  NaN  1.0
2  NaN  1.0  NaN  3.0
3  NaN  3.0  NaN  4.0

When filling using a DataFrame, replacement happens along
the same column names and same indices

>>> df2 = pd.DataFrame(np.zeros((4, 4)), columns=list("ABCE"))
>>> df.fillna(df2)
     A    B    C    D
0  0.0  2.0  0.0  0.0
1  3.0  4.0  0.0  1.0
2  0.0  0.0  0.0  NaN
3  0.0  3.0  0.0  4.0

Note that column D is not affected since it is not present in df2.
File:      ~/Documents/colombia-elections-analysis-app/.venv/lib/python3.13/site-packages/pandas/core/generic.py
Type:      function