In [4]:
import pandas as pd
from pathlib import Path

path = Path("/home/juan-wills/Documents/colombia-elections-analysis-app/data/raw/senate")
s_2006 = pd.read_csv(path / '2006_senado.csv')
s_2006.head()

,id_electoral,ano,tipo_eleccion,fecha_eleccion,coddpto,departamento,codmpio,municipio,circunscripcion,codigo_partido,codigo_lista,primer_apellido,segundo_apellido,nombres,votos,curules
0,220060002,2006,Senado,Marzo 12,5.0,ANTIOQUIA,5001.0,MEDELLIN,Indígena,19910001.0,0,NaN,NaN,MOVIMIENTO AUTORIDADES INDIGENAS DE COLOMBIA ...,251,0
1,220060001,2006,Senado,Marzo 12,5.0,ANTIOQUIA,5001.0,MEDELLIN,Nacional,20000203.0,0,NaN,NaN,MOVIMIENTO DE PARTICIPACION COMUNITARIA MPC,982,0
2,220060002,2006,Senado,Marzo 12,5.0,ANTIOQUIA,5001.0,MEDELLIN,Indígena,19910002.0,0,NaN,NaN,MOVIMIENTO ALIANZA SOCIAL INDIGENA ASI,785,0
3,220060001,2006,Senado,Marzo 12,5.0,ANTIOQUIA,5001.0,MEDELLIN,Nacional,20000036.0,0,NaN,NaN,MOVIMIENTO MIRA,4957,0
4,220060001,2006,Senado,Marzo 12,5.0,ANTIOQUIA,5001.0,MEDELLIN,Nacional,19980014.0,0,NaN,NaN,MOVIMIENTO COMUNAL Y COMUNITARIO DE COLOMBIA,217,0

In [ ]:
months = ['Enero', 'Febrero', 'Marzo', 'Abril', 'Mayo', 'Junio', 'Julio', 'Agosto', 'Septiembre', 'Octubre', 'noviembre', 'Diciembre']
month_dict = {month:str(i) for i, month in enumerate(months)}
dtypes = {
    "id_electoral":pd.Int64Dtype(),
    "ano":str,
    "tipo_eleccion":str,
    "coddpto":pd.Int64Dtype(),
    "departamento":str,
    "codmpio":pd.Int64Dtype(),
    "municipio":str,
    "circunscripcion":str,
    "codigo_partido":pd.Int64Dtype(),
    "codigo_lista":pd.Int64Dtype(),
    "primer_apellido":str,
    "segundo_apellido":str,
    "nombres":str,
    "votos":pd.Int64Dtype(),
    "curules":pd.Int64Dtype(),
    "defaultdict":str
}


s_2006 = pd.read_csv(path / '2006_senado.csv',
                        dtype=dtypes,
                        converters=custom_dtypes,
                        encoding='utf-8',
                        sep=',',
                        engine='python', 
                        skipinitialspace=True
                    )

# print(s_2006.dtypes)
s_2006.head()

,id_electoral,ano,tipo_eleccion,fecha_eleccion,coddpto,departamento,codmpio,municipio,circunscripcion,codigo_partido,codigo_lista,primer_apellido,segundo_apellido,nombres,votos,curules
0,220060002,2006,Senado,2 12,5,ANTIOQUIA,5001,MEDELLIN,Indígena,19910001,0,NaN,NaN,MOVIMIENTO AUTORIDADES INDIGENAS DE COLOMBIA ...,251,0
1,220060001,2006,Senado,2 12,5,ANTIOQUIA,5001,MEDELLIN,Nacional,20000203,0,NaN,NaN,MOVIMIENTO DE PARTICIPACION COMUNITARIA MPC,982,0
2,220060002,2006,Senado,2 12,5,ANTIOQUIA,5001,MEDELLIN,Indígena,19910002,0,NaN,NaN,MOVIMIENTO ALIANZA SOCIAL INDIGENA ASI,785,0
3,220060001,2006,Senado,2 12,5,ANTIOQUIA,5001,MEDELLIN,Nacional,20000036,0,NaN,NaN,MOVIMIENTO MIRA,4957,0
4,220060001,2006,Senado,2 12,5,ANTIOQUIA,5001,MEDELLIN,Nacional,19980014,0,NaN,NaN,MOVIMIENTO COMUNAL Y COMUNITARIO DE COLOMBIA,217,0

In [ ]:
# for i in month_dict.items():
#     print(i)
#     break

# re.sub(month, i, s)
# "Hi mayo".replace("Mayo", "5")

False